
version: '3.1'
services:

  db:
    image: mysql:5.7
    container_name: app_mysql
    restart: always
    volumes:
      - .docker/data/db:/var/lib/mysql
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

  php:
    build:
      context: .docker/php
      args:
        - WITH_XDEBUG=true
    env_file: .env
    container_name: app_php
    restart: always
    volumes:
      - .docker/php/php.ini:/usr/local/etc/php/php.ini
      - ${SYMFONY_APP}:/var/www/backend
      - ./logs/backend:/var/www/backend/var/log:cached
    environment:
      - maildev_host=app_maildev
    links:
      - db
      - elk
    depends_on:
      - maildev
      - db

  maildev:
    image: djfarrelly/maildev
    container_name: app_maildev
    ports:
      - 8002:80      
 
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: app_phpmyadmin
    restart: always
    ports:
      - 8080:80
    links:
      - db
    environment:
      PMA_HOST: db

  nginx:
      build: .docker/nginx
      ports:
          - 80:80
      links:
        - php
      volumes:
          - ./logs/nginx:/var/log/nginx:cached
          - .docker/nginx/nginx.conf:/etc/nginx/nginx.conf
          - .docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
          - ${SYMFONY_APP}:/var/www/backend
